# Generated by Django 5.1.3 on 2024-12-31 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='active_users',
            field=models.ManyToManyField(blank=True, related_name='active_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
