# Generated by Django 5.1.3 on 2024-12-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_room_active_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
