# Generated by Django 5.1.3 on 2025-01-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='images/default-avatar.png', upload_to='profile_pictures/'),
        ),
    ]
